"""Add status and error_message to Credential

Revision ID: 212342e9d042
Revises: 50c0fa74a505
Create Date: 2026-03-13 16:03:36.180951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212342e9d042'
down_revision: Union[str, Sequence[str], None] = '50c0fa74a505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('status', sa.Text(), nullable=True))
    op.add_column('credentials', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'error_message')
    op.drop_column('credentials', 'status')
    # ### end Alembic commands ###

