"""Add SystemEvent table

Revision ID: e462297b3a9e
Revises: 001_full_schema
Create Date: 2026-03-25 21:46:16.221851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e462297b3a9e'
down_revision: Union[str, Sequence[str], None] = '001_full_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_level'), 'system_events', ['level'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_level'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###
