#!/usr/bin/env python3
"""
UnifyRoute Setup Utility
========================
Commands:
  install    — First-time interactive setup (default)
  refresh    — Re-sync deps, rebuild GUI, run migrations (optionally save config)
  uninstall  — Clean up everything (optionally save config)
"""
from __future__ import annotations
import argparse
import datetime
import hashlib
import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

# Force UTF-8 encoding for output on Windows
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# ── Project root is the parent of this script's directory ─────────────────────
SCRIPT_DIR = Path(__file__).parent.resolve()
ROOT = SCRIPT_DIR.parent
ENV_FILE = ROOT / ".env"
SAMPLE_ENV = ROOT / "sample.env"
VENV_DIR = ROOT / ".venv"


# ── Helpers ────────────────────────────────────────────────────────────────────

def c(code: str, text: str) -> str:
    """ANSI colour helper."""
    CODES = {"red": "31", "green": "32", "yellow": "33", "cyan": "36", "bold": "1", "reset": "0"}
    return f"\033[{CODES.get(code, '0')}m{text}\033[0m"


def banner(text: str):
    print("\n" + c("cyan", "─" * 60))
    print(c("bold", f"  {text}"))
    print(c("cyan", "─" * 60))


def ok(msg: str):   print(c("green", f"  ✅ {msg}"))
def warn(msg: str): print(c("yellow", f"  ⚠️  {msg}"))
def err(msg: str):  print(c("red", f"  ❌ {msg}"))
def info(msg: str): print(f"  ℹ️  {msg}")


def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    """Prompt user for input with an optional default."""
    hint = f" [{default}]" if default else ""
    full_prompt = f"  {prompt}{hint}: "
    if secret:
        import getpass
        val = getpass.getpass(full_prompt)
    else:
        val = input(full_prompt)
    return val.strip() or default


def ask_bool(prompt: str, default: bool = True) -> bool:
    default_hint = "Y/n" if default else "y/N"
    val = input(f"  {prompt} [{default_hint}]: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def run(cmd: list[str], cwd: Path = ROOT, check: bool = True) -> int:
    """Run a command, streaming output."""
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(cwd))
    if check and result.returncode != 0:
        err(f"Command failed with exit code {result.returncode}")
        sys.exit(result.returncode)
    return result.returncode


def set_env_var(key: str, value: str, env_content: dict) -> dict:
    """Update a key in the env content dict."""
    env_content[key] = value
    return env_content


def read_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict (preserving comments as special keys)."""
    result: dict[str, str] = {}
    if not path.exists():
        return result
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or not stripped:
            continue
        if "=" in stripped:
            key, _, val = stripped.partition("=")
            result[key.strip()] = val.strip()
    return result


def write_env_file(path: Path, config: dict[str, str], header: str = ""):
    """Write a dict to a .env file in a readable grouped format."""
    lines = []
    if header:
        lines.append(f"# Generated by unifyroute setup on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")

    # Group output for readability
    groups = {
        "# ── Database ──────────────────────────────────────────────────────────────": [
            "DB_BACKEND", "SQLITE_PATH",
        ],
        "# ── Application ────────────────────────────────────────────────────────────": [
            "PORT", "HOST", "API_BASE_URL",
        ],
        "# ── Redis ───────────────────────────────────────────────────────────────────": [
            "REDIS_URL",
        ],
        "# ── Secrets ─────────────────────────────────────────────────────────────────": [
            "MASTER_PASSWORD", "VAULT_MASTER_KEY", "JWT_SECRET",
        ],
    }

    written = set()
    for section_header, keys in groups.items():
        section_lines = []
        for k in keys:
            if k in config:
                section_lines.append(f"{k}={config[k]}")
                written.add(k)
        if section_lines:
            lines.append(section_header)
            lines.extend(section_lines)
            lines.append("")

    # Write remaining keys not in any group
    remaining = [(k, v) for k, v in config.items() if k not in written]
    if remaining:
        lines.append("# ── Other ──────────────────────────────────────────────────────────────────")
        for k, v in remaining:
            lines.append(f"{k}={v}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def backup_config(reason: str = ""):
    """Backup the current .env file and SQLite database."""
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    backed_up = []

    if ENV_FILE.exists():
        env_backup = ROOT / f".env.backup.{ts}"
        shutil.copy(ENV_FILE, env_backup)
        backed_up.append(env_backup.name)
    else:
        info("No .env to back up.")

    db_file = ROOT / "data" / "unifyroute.db"
    if db_file.exists():
        db_backup = ROOT / f".db.backup.{ts}"
        shutil.copy(db_file, db_backup)
        backed_up.append(db_backup.name)
    else:
        info("No database to back up.")
        
    if backed_up:
        reason_str = f" ({reason})" if reason else ""
        ok(f"Backed up: {', '.join(backed_up)}{reason_str}")
        return ts
    return None


def find_saved_configs() -> list[str]:
    """Find all backup timestamps in the project root, newest first.
    A valid backup has at least a .env.backup.* file.
    """
    backups = sorted(
        ROOT.glob(".env.backup.*"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    # Return just the timestamp part
    return [p.name.replace(".env.backup.", "") for p in backups]


def restore_config(ts: str) -> dict[str, str]:
    """Restore configuration and database from a backup timestamp.

    Copies the backup files to their original locations.
    """
    env_backup = ROOT / f".env.backup.{ts}"
    if env_backup.exists():
        shutil.copy(env_backup, ENV_FILE)
        config = read_env_file(ENV_FILE)
        ok(f"Configuration restored from {env_backup.name}")
        
        # Show restored values (mask secrets)
        secret_keys = {"MASTER_PASSWORD", "VAULT_MASTER_KEY", "JWT_SECRET"}
        for key, val in config.items():
            if key in secret_keys:
                display = val[:3] + "***" if len(val) > 3 else "***"
            else:
                display = val
            info(f"  {key} = {display}")
    else:
        config = {}

    db_backup = ROOT / f".db.backup.{ts}"
    if db_backup.exists():
        data_dir = ROOT / "data"
        data_dir.mkdir(exist_ok=True)
        db_file = data_dir / "unifyroute.db"
        shutil.copy(db_backup, db_file)
        ok(f"Database restored from {db_backup.name}")

    return config


def find_uv() -> str:
    """Find the uv binary."""
    uv = shutil.which("uv")
    if uv:
        return uv
    home_uv = Path.home() / ".local" / "bin" / "uv"
    if home_uv.exists():
        return str(home_uv)
    err("'uv' is not installed. Install with:\n    curl -LsSf https://astral.sh/uv/install.sh | sh")
    sys.exit(1)


def find_npm() -> str:
    npm = shutil.which("npm")
    if not npm:
        err("'npm' is not installed. Please install Node.js.")
        sys.exit(1)
    return npm


def find_docker() -> bool:
    docker = shutil.which("docker")
    if not docker:
        return False
    result = subprocess.run(["docker", "info"], capture_output=True)
    return result.returncode == 0


def check_prerequisites() -> bool:
    """
    Run the prerequisite checker and exit if requirements aren't met.
    Returns True if all prerequisites are satisfied, exits with error if not.
    """
    banner("Checking Prerequisites")
    
    check_script = SCRIPT_DIR / "check_prerequisites.py"
    if not check_script.exists():
        err(f"Prerequisite check script not found at {check_script}")
        sys.exit(1)
    
    # Run the prerequisite checker, inheriting the current environment
    # This is important for tools installed in the current venv
    result = subprocess.run(
        [sys.executable, str(check_script)],
        cwd=str(ROOT),
        env=os.environ.copy()  # Inherit parent environment (important for venv PATH)
    )
    
    if result.returncode == 0:
        ok("All prerequisites are met!")
        return True
    else:
        print()
        banner("Prerequisites Not Met")
        print(c("red", "  ❌ Setup cannot proceed. Please install the missing prerequisites listed above."))
        print()
        print("  To verify prerequisites again, run:")
        print(f"    {c('bold', 'python scripts/check_prerequisites.py')} (any OS)")
        print(f"    {c('bold', './scripts/check_prerequisites.sh')} (macOS/Linux)")
        print(f"    {c('bold', '.\\\\scripts\\\\check_prerequisites.bat')} (Windows)")
        print()
        sys.exit(1)


def create_venv():
    """Create a Python virtual environment in .venv."""
    if VENV_DIR.exists():
        ok(f"Virtual environment already exists at {VENV_DIR.relative_to(ROOT)}")
        return
    info(f"Creating virtual environment at {VENV_DIR.relative_to(ROOT)}...")
    uv = find_uv()
    if uv:
        subprocess.run([uv, "venv", str(VENV_DIR)], check=True, cwd=str(ROOT))
    else:
        subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)], check=True)
    ok("Virtual environment created.")


def get_venv_python() -> str:
    """Get the path to the Python executable in the venv."""
    if sys.platform == "win32":
        return str(VENV_DIR / "Scripts" / "python.exe")
    else:
        return str(VENV_DIR / "bin" / "python")


def find_or_install_uv(venv_python: str) -> str:
    """Find uv or install it in the venv, fall back to pip."""
    # Try to find uv in PATH first
    uv = shutil.which("uv")
    if uv:
        return uv

    # Try home .local/bin on Unix
    home_uv = Path.home() / ".local" / "bin" / "uv"
    if home_uv.exists():
        return str(home_uv)

    # Try to find or install uv in venv
    info("Attempting to install 'uv' in virtual environment...")
    result = subprocess.run(
        [venv_python, "-m", "pip", "install", "-q", "uv"],
        capture_output=True
    )

    if result.returncode == 0:
        if sys.platform == "win32":
            uv_path = VENV_DIR / "Scripts" / "uv.exe"
        else:
            uv_path = VENV_DIR / "bin" / "uv"
        if uv_path.exists():
            ok("'uv' installed in virtual environment.")
            return str(uv_path)

    # Fall back to using pip directly
    warn("Could not install 'uv'. Will use pip for dependency management.")
    return None


def _remove_unifyroute_images():
    """Remove any locally-built Docker images whose name starts with 'unifyroute'.

    `docker compose down --rmi all` only removes images that compose itself
    manages (e.g. redis).  Images built from project Dockerfiles and
    tagged unifyroute* must be removed separately.
    """
    result = subprocess.run(
        ["docker", "images", "--filter", "reference=unifyroute*",
         "--format", "{{.Repository}}:{{.Tag}}"],
        capture_output=True, text=True
    )
    image_ids = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if not image_ids:
        info("No locally-built unifyroute* images found.")
        return
    for img in image_ids:
        info(f"Removing image: {img}")
        subprocess.run(["docker", "rmi", "-f", img], capture_output=False)


def _remove_unifyroute_containers():
    """Force-remove ALL containers (running or stopped) whose name starts with 'unifyroute'.

    `docker compose down` only removes containers it manages via the compose
    project.  Containers started outside compose or with a different project name
    must be cleaned up explicitly.
    """
    result = subprocess.run(
        ["docker", "ps", "-a",
         "--filter", "name=unifyroute",
         "--format", "{{.Names}}"],
        capture_output=True, text=True
    )
    names = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if not names:
        info("No unifyroute* containers found.")
        return
    for name in names:
        info(f"Removing container: {name}")
        subprocess.run(["docker", "rm", "-f", name], capture_output=False)


# ── Commands ───────────────────────────────────────────────────────────────────

def cmd_install():
    """Interactive first-time setup."""
    print(c("bold", "\n🚀 UnifyRoute Setup — First-Time Install\n"))
    
    # Check prerequisites before proceeding
    check_prerequisites()

    config: dict[str, str] = {}
    restored = False

    # ── Check for saved configurations ─────────────────────────────
    saved_configs = find_saved_configs()
    if saved_configs:
        banner("Saved Configurations Found")
        print("  The following saved configurations were found:\n")
        for i, ts in enumerate(saved_configs, 1):
            env_backup = ROOT / f".env.backup.{ts}"
            mtime = datetime.datetime.fromtimestamp(env_backup.stat().st_mtime)
            
            # Check what's included
            includes = [".env"]
            if (ROOT / f".db.backup.{ts}").exists():
                includes.append("unifyroute.db")
                
            print(f"    {i}. Backup from {mtime.strftime('%Y-%m-%d %H:%M:%S')}  [includes: {', '.join(includes)}]")
        print()

        if ask_bool("Would you like to restore a previously saved configuration?", default=True):
            if len(saved_configs) == 1:
                choice = 1
            else:
                choice_str = ask(f"Which backup to restore? [1-{len(saved_configs)}]", "1")
                try:
                    choice = int(choice_str)
                    if choice < 1 or choice > len(saved_configs):
                        raise ValueError
                except ValueError:
                    warn(f"Invalid choice. Using most recent backup.")
                    choice = 1

            selected_ts = saved_configs[choice - 1]
            config = restore_config(selected_ts)
            restored = True
            ok("Configuration and database restored! Skipping interactive configuration steps.")

    if not restored:
        # ── 1. Database ────────────────────────────────────────────────
        banner("1. Database Configuration")
        print("  UnifyRoute uses SQLite for local data storage.")

        config["DB_BACKEND"] = "sqlite"

        sqlite_path = ask("SQLite file path", "data/unifyroute.db")
        config["SQLITE_PATH"] = sqlite_path

        # ── 2. Application ──────────────────────────────────────────────
        banner("2. Application Settings")
        app_port = ask("Application port", "6565")
        app_host = ask("Application host", "localhost")
        api_base = ask("API base URL", f"http://{app_host}:{app_port}")

        config["PORT"] = app_port
        config["HOST"] = app_host
        config["API_BASE_URL"] = api_base
        config["REDIS_URL"] = f"redis://localhost:6379/0"

        # ── 3. Master Password ─────────────────────────────────────────
        banner("3. Master Password")
        print("  This password is used to:")
        print("    • Log in to the UnifyRoute GUI")
        print("    • Authorize CLI token operations (unifyroute get token, create token, etc.)")
        while True:
            master_pw = ask("Master password", secret=True)
            if len(master_pw) < 8:
                warn("Password must be at least 8 characters.")
                continue
            confirm_pw = ask("Confirm master password", secret=True)
            if master_pw != confirm_pw:
                warn("Passwords do not match. Try again.")
                continue
            break
        config["MASTER_PASSWORD"] = master_pw
        ok("Master password set.")

        # ── 4. Secrets ──────────────────────────────────────────────────
        banner("4. Generating Secrets")

        # Read existing secrets from .env if present (for idempotency)
        existing = read_env_file(ENV_FILE)

        vault_key = existing.get("VAULT_MASTER_KEY", "")
        if not vault_key:
            vault_key = _generate_fernet_key()
            ok("VAULT_MASTER_KEY generated.")
        else:
            ok("VAULT_MASTER_KEY already set — keeping existing.")
        config["VAULT_MASTER_KEY"] = vault_key

        jwt_secret = existing.get("JWT_SECRET", "")
        if not jwt_secret:
            jwt_secret = secrets.token_hex(32)
            ok("JWT_SECRET generated.")
        else:
            ok("JWT_SECRET already set — keeping existing.")
        config["JWT_SECRET"] = jwt_secret

        # ── 5. Encrypt Master Password ──────────────────────────────────
        if not config["MASTER_PASSWORD"].startswith("enc:"):
            info("Encrypting master password for security...")
            config["MASTER_PASSWORD"] = _encrypt_password(config["MASTER_PASSWORD"], config["VAULT_MASTER_KEY"])

    # ── 6. Write .env ───────────────────────────────────────────────
    banner("6. Writing .env")
    write_env_file(ENV_FILE, config, header=True)
    ok(f".env written to {ENV_FILE}")

    # ── 6. Create virtual environment ────────────────────────────────
    banner("6. Creating Virtual Environment")
    create_venv()
    venv_python = get_venv_python()

    # ── 7. Installing Python Dependencies ────────────────────────────
    banner("7. Installing Python Dependencies in Virtual Environment")
    
    # Upgrade pip first
    print(f"  Upgrading pip...")
    subprocess.run([venv_python, "-m", "pip", "install", "-q", "--upgrade", "pip"], check=False)
    
    # Try using uv sync --all-packages (syncs EVERY workspace member into .venv)
    uv = find_or_install_uv(venv_python)
    if uv:
        # UV_LINK_MODE=copy avoids hardlink issues on Windows/some Linux filesystems
        env_with_uv = {**os.environ, "UV_LINK_MODE": "copy"}
        print(f"  Installing all workspace packages via uv sync --all-packages...")
        result = subprocess.run([uv, "sync", "--all-packages"], cwd=str(ROOT), env=env_with_uv)
        if result.returncode != 0:
            warn("uv sync --all-packages had issues. Falling back to pip...")
            uv = None
    
    # Pip fallback if uv is unavailable
    if not uv:
        print(f"  Installing packages via pip into venv...")
        for package_dir in ["shared", "api-gateway", "router", "launcher", "credential-vault", "quota-poller"]:
            pkg_path = ROOT / package_dir
            if pkg_path.exists():
                print(f"    Installing {package_dir}...")
                result = subprocess.run(
                    [venv_python, "-m", "pip", "install", "-q", "-e", str(pkg_path)],
                    cwd=str(ROOT)
                )
                if result.returncode != 0:
                    warn(f"Failed to install {package_dir}, but continuing...")
        
        print(f"    Installing core dependencies...")
        subprocess.run(
            [venv_python, "-m", "pip", "install", "-q", "uvicorn", "fastapi", "sqlalchemy", "alembic"],
            cwd=str(ROOT), check=False
        )
    
    ok("Python dependencies installed in virtual environment.")

    # ── 8. Frontend ─────────────────────────────────────────────────
    banner("8. Building Frontend")
    npm = find_npm()
    gui_dir = ROOT / "gui"
    run([npm, "install"], cwd=gui_dir)
    run([npm, "run", "build"], cwd=gui_dir)
    ok("Frontend built.")

    # ── 9. Database migrations ──────────────────────────────────────
    banner("9. Running Database Migrations")
    env = {**os.environ, **{k: v for k, v in config.items()}}
    upgrade_cmd = [uv, "run", "--package", "shared", "alembic", "upgrade", "head"] if uv else [venv_python, "-m", "alembic", "upgrade", "head"]
    result = subprocess.run(upgrade_cmd, cwd=str(ROOT), env=env)

    if result.returncode != 0:
        # If it failed, it might be because the DB has an old revision ID that we deleted
        # during consolidation. If we just restored, we should stamp it.
        if restored:
            warn("Migration failed. Attempting to stamp database to consolidated revision...")
            stamp_cmd = [uv, "run", "--package", "shared", "alembic", "stamp", "001_full_schema"] if uv else [venv_python, "-m", "alembic", "stamp", "001_full_schema"]
            result = subprocess.run(stamp_cmd, cwd=str(ROOT), env=env)
            if result.returncode == 0:
                ok("Database stamped to 001_full_schema. Retrying upgrade...")
                upgrade_cmd = [uv, "run", "--package", "shared", "alembic", "upgrade", "head"] if uv else [venv_python, "-m", "alembic", "upgrade", "head"]
                result = subprocess.run(upgrade_cmd, cwd=str(ROOT), env=env)

        if result.returncode != 0:
            err("Migration failed. Check the error above.")
            sys.exit(result.returncode)
    ok("Database schema up to date.")

    # ── 10. Initial admin key ───────────────────────────────────────
    banner("10. Creating Initial Admin API Token")
    if uv:
        result = subprocess.run(
            [uv, "run", "--package", "shared", "python", "scripts/create-key.py",
             f"Admin Setup {int(datetime.datetime.now().timestamp())}", "--type", "admin"],
            cwd=str(ROOT), env=env
        )
    else:
        result = subprocess.run(
            [venv_python, "scripts/create-key.py",
             f"Admin Setup {int(datetime.datetime.now().timestamp())}", "--type", "admin"],
            cwd=str(ROOT), env=env
        )
    if result.returncode != 0:
        warn("Could not create admin key automatically. Run: ./unifyroute create token admin")

    # ── Done ─────────────────────────────────────────────────────────
    api_base = config.get("API_BASE_URL", "http://localhost:6565")
    banner("✅ Setup Complete!")
    print(f"\n  Start the app with:  {c('bold', './unifyroute start')}")
    print(f"  Open:                {c('cyan', api_base)}")
    if restored:
        print(f"  Login with the master password from your restored configuration.\n")
    else:
        print(f"  Login with the master password you set above.\n")


def cmd_refresh():
    """Re-sync deps, rebuild GUI, run migrations."""
    print(c("bold", "\n🔄 UnifyRoute Setup — Refresh\n"))
    
    # Check prerequisites before proceeding
    check_prerequisites()
    
    if ask_bool("Save current configuration before refresh?", default=True):
        backup_config("refresh")

    if not VENV_DIR.exists():
        err("No virtual environment found. Run './unifyroute setup' first.")
        sys.exit(1)

    venv_python = get_venv_python()

    banner("1. Installing/Syncing Python Dependencies in Virtual Environment")
    
    # Upgrade pip first
    print(f"  Upgrading pip...")
    subprocess.run([venv_python, "-m", "pip", "install", "-q", "--upgrade", "pip"], check=False)
    
    uv = find_or_install_uv(venv_python)
    if uv:
        # Set UV_LINK_MODE=copy to avoid hardlink issues on Windows
        env_with_uv = {**os.environ, "UV_LINK_MODE": "copy"}
        print(f"  Installing via uv sync...")
        result = subprocess.run([uv, "sync"], cwd=str(ROOT), env=env_with_uv)
        if result.returncode != 0:
            warn("uv sync had issues. Falling back to pip...")
            uv = None
    
    # Always ensure all packages are in venv
    if not uv:
        print(f"  Installing packages via pip into venv...")
        for package_dir in ["shared", "api-gateway", "router", "launcher", "credential-vault", "quota-poller"]:
            pkg_path = ROOT / package_dir
            if pkg_path.exists():
                print(f"    Installing {package_dir}...")
                result = subprocess.run(
                    [venv_python, "-m", "pip", "install", "-q", "-e", str(pkg_path)],
                    cwd=str(ROOT)
                )
                if result.returncode != 0:
                    warn(f"Failed to install {package_dir}, but continuing...")
        
        # Ensure core dependencies
        print(f"    Installing core dependencies...")
        subprocess.run(
            [venv_python, "-m", "pip", "install", "-q", "uvicorn", "fastapi", "sqlalchemy", "alembic"],
            cwd=str(ROOT),
            check=False
        )
    
    ok("Python dependencies installed in virtual environment.")

    banner("2. Rebuilding Frontend")
    npm = find_npm()
    gui_dir = ROOT / "gui"
    run([npm, "install"], cwd=gui_dir)
    run([npm, "run", "build"], cwd=gui_dir)
    ok("Frontend rebuilt.")

    banner("3. Running Database Migrations")
    result = subprocess.run(
        [venv_python, "-m", "alembic", "upgrade", "head"],
        cwd=str(ROOT)
    )
    
    if result.returncode != 0:
        warn("Migration failed. Attempting to stamp and retry...")
        subprocess.run(
            [venv_python, "-m", "alembic", "stamp", "001_full_schema"],
            cwd=str(ROOT)
        )
        result = subprocess.run(
            [venv_python, "-m", "alembic", "upgrade", "head"],
            cwd=str(ROOT)
        )

    if result.returncode != 0:
        err("Migrations failed to apply.")
    else:
        ok("Migrations applied.")
    print(c("green", "\n  ✅ Refresh complete!\n"))


def cmd_uninstall():
    """Clean up everything."""
    print(c("bold", "\n🗑️  UnifyRoute Setup — Uninstall\n"))
    warn("This will stop all UnifyRoute services and remove local data, venv, and build files.")
    if not ask_bool("Are you sure you want to uninstall?", default=False):
        info("Uninstall cancelled.")
        sys.exit(0)
    if ask_bool("Save current configuration before uninstall?", default=True):
        backup_config("uninstall")

    banner("1. Stopping Processes")
    if sys.platform == "win32":
        subprocess.run(["taskkill", "/IM", "python.exe", "/F"], capture_output=True)
    else:
        subprocess.run(["pkill", "-f", "launcher.main:app"], capture_output=True)
    ok("Standalone processes stopped (if any).")

    # Stop systemd service (Linux only)
    if sys.platform != "win32":
        result = subprocess.run(["systemctl", "is-active", "--quiet", "unifyroute.service"], capture_output=True)
        if result.returncode == 0:
            subprocess.run(["sudo", "systemctl", "stop", "unifyroute.service"])
            subprocess.run(["sudo", "systemctl", "disable", "unifyroute.service"])
            subprocess.run(["sudo", "rm", "-f", "/etc/systemd/system/unifyroute.service"])
            subprocess.run(["sudo", "systemctl", "daemon-reload"])
            ok("Systemd service stopped and disabled.")

    banner("2. Docker Cleanup")
    if find_docker():
        dc_file = ROOT / "docker-compose.yml"
        if dc_file.exists():
            print()
            print("  What would you like to clean up?")
            remove_containers = ask_bool("  Remove Docker containers and volumes?", default=True)
            remove_images = ask_bool("  Remove Docker images?", default=False)

            if not remove_containers and not remove_images:
                info("Docker cleanup skipped.")
            elif remove_containers and remove_images:
                # Stop compose-managed containers, remove volumes + compose-known images
                subprocess.run(
                    ["docker", "compose", "down", "-v", "--rmi", "all"],
                    cwd=str(ROOT)
                )
                # Also clean up any unifyroute* containers/images not tracked by compose
                _remove_unifyroute_containers()
                _remove_unifyroute_images()
                ok("Docker containers, volumes, and images removed.")
            elif remove_containers:
                # Stop compose-managed containers + remove volumes
                subprocess.run(
                    ["docker", "compose", "down", "-v"],
                    cwd=str(ROOT)
                )
                # Also clean up any unifyroute* containers not tracked by compose
                _remove_unifyroute_containers()
                ok("Docker containers and volumes removed.")
            else:
                # Images only — stop containers first to release image locks,
                # then remove all unifyroute* images.
                info("Stopping containers to free image locks, then removing images...")
                subprocess.run(
                    ["docker", "compose", "down", "--rmi", "all"],
                    cwd=str(ROOT)
                )
                _remove_unifyroute_containers()
                _remove_unifyroute_images()
                ok("Docker images removed (containers were stopped to release image locks).")
        else:
            info("docker-compose.yml not found — skipping Docker cleanup.")
    else:
        info("Docker not available — skipping.")

    banner("3. Removing Local Files")
    dirs_to_remove = [
        ROOT / "data",
        ROOT / ".venv",
        ROOT / "gui" / "node_modules",
        ROOT / "gui" / "dist",
    ]
    for d in dirs_to_remove:
        if d.exists():
            shutil.rmtree(d)
            ok(f"Removed {d.relative_to(ROOT)}")
        else:
            info(f"Already absent: {d.relative_to(ROOT)}")

    banner("✅ Uninstall Complete!")
    print("  To reinstall: ./unifyroute setup")
    print("  To fully delete: cd .. && rm -rf unifyroute\n")


def _generate_fernet_key() -> str:
    """Generate a Fernet-compatible base64 key without importing cryptography."""
    import base64
    raw = secrets.token_bytes(32)
    return base64.urlsafe_b64encode(raw).decode("utf-8")


def _encrypt_password(password: str, vault_key_b64: str) -> str:
    """Try to encrypt the password using AES-256-GCM. Requires cryptography."""
    if not password:
        return ""
    
    try:
        import base64
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        
        key_bytes = base64.urlsafe_b64decode(vault_key_b64.encode('utf-8'))
        aesgcm = AESGCM(key_bytes)
        iv = os.urandom(12)
        ciphertext = aesgcm.encrypt(iv, password.encode('utf-8'), None)
        
        iv_b64 = base64.urlsafe_b64encode(iv).decode('utf-8')
        ct_b64 = base64.urlsafe_b64encode(ciphertext).decode('utf-8')
        return f"enc:{iv_b64}:{ct_b64}"
    except (ImportError, Exception) as e:
        warn(f"Automatic password encryption failed: {e}. Storing as plain text.")
        return password


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="UnifyRoute Setup Utility",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  install    First-time interactive setup (default)
  refresh    Re-sync deps, rebuild GUI, run migrations
  uninstall  Stop services and clean up local files
""",
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=["install", "refresh", "uninstall"],
        default="install",
        help="Action to perform (default: install)",
    )
    args = parser.parse_args()

    if args.command == "install":
        cmd_install()
    elif args.command == "refresh":
        cmd_refresh()
    elif args.command == "uninstall":
        cmd_uninstall()


if __name__ == "__main__":
    main()
